app_id: "85990ecd-c674-4449-abff-7418c0f5403a"
app_secret: "T4xb_XG9FAcb_P4ys_2WN[ICUHG2zwM-"
redirect: "http://localhost:8000/tutorial/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"


